% Supplementary figures


```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)

```



```{r warning=FALSE, message=FALSE, echo=FALSE}

library(EnvRtype)
library(rio)
library(factoextra)
library(FactoMineR)
library(ggrepel)
library(ggh4x)
library(superheat)
library(ggridges)
library(metan)
library(rnaturalearth)
library(lme4)
library(lmerTest)
library(broom.mixed)
library(tidyverse)
library(kableExtra)

```



```{r  warning=FALSE, message=FALSE, echo=FALSE}

print_table = function(df,
                       caption,
                       digits = 4,
                       full_width = TRUE,
                       col.names = NA,
                       longtable = FALSE,
                       scape = FALSE,
                       html_opt = c("striped", "responsive")){
  kable(df,
        align  = "l",
        col.names = col.names,
        booktabs = T,
        digits = digits,
        format = "html",
        linesep = "",
        caption = caption,
        escape = scape,
        longtable = longtable) %>%
    kable_classic(lightable_options = "striped", html_font = "sans", full_width = full_width) %>%
    kable_styling(bootstrap_options = html_opt)
}


# get variance components
get_vcomp <- function(model){
  model |> 
    tidy(effects = "ran_pars") |> 
    mutate(variance = estimate ^ 2) |> 
    dplyr::select(group, variance)
}

# get lrt
get_lrt <- function(model){
  model |> 
    ranova() |> 
    as.data.frame() |> 
    mutate(p_val = `Pr(>Chisq)`) |> 
    rownames_to_column("term") |> 
    dplyr::select(term, AIC, LRT, p_val) |> 
    mutate(term = str_sub(term, start = 6, end = -2))
}


```


# Table S1 {-}
```{r echo=FALSE}
lrt <- 
  import("data/lrt.xlsx") |> 
mutate(across(BTL:PH, function(x){
  as.character(signif(x, 4))
}))

print_table(lrt, "Likelihood Ratio Test (LRT) for the random effects for each analyzed trait")
```





# Table S2 {-}
```{r echo=FALSE}
mgidi_mod <- readRDS("data/mgidi.Rdata")

variances <-
  list(
    ME1 = gmd(mgidi_mod$mgidi[[1]], "PCA"),
    ME2 = gmd(mgidi_mod$mgidi[[2]], "PCA"),
    ME3 = gmd(mgidi_mod$mgidi[[3]], "PCA"),
    ME4 = gmd(mgidi_mod$mgidi[[4]], "PCA")
  ) |>
  bind_rows(.id = "model")

print_table(variances, caption = "Eigenvalues and explained variance for the factor analysis acroos all environments (ALL) and within each mega-environments (ME1, ME2, ME3, and ME4).")

```




```{r echo=FALSE}
factors <-
  list(
    ME1 = gmd(mgidi_mod$mgidi[[1]], "sel_dif"),
    ME2 = gmd(mgidi_mod$mgidi[[2]], "sel_dif"),
    ME3 = gmd(mgidi_mod$mgidi[[3]], "sel_dif"),
    ME4 = gmd(mgidi_mod$mgidi[[4]], "sel_dif")
  ) |>
  bind_rows(.id = "model") |> 
  select(model, VAR, Factor) |> 
  rename(ME = model, TRAIT = VAR)
```




# Table S3 {-}
```{r echo=FALSE}
gains <- 
  import("data/gains.xlsx") |> 
  left_join(factors) |> 
  relocate(Factor, .after = TRAIT) |> 
  arrange(ME, Factor)

gains |> 
  set_names(c("ME", "TRAIT", "Factor", "Xo", "Xs", "SD", "Xo", "Xs", "SD")) |> 
  print_table(caption = "Selecion differentials for mean performance and stability of the studied traits in the four delineated mega environments.") |> 
  add_header_above(c(" " = 3, "Mean performance" = 3, "Stability" = 3),
                   align = "l")

```



