% Supplementary figures 


```{r global_options, include = FALSE}
knitr::opts_chunk$set(cache = FALSE,
                      comment = "##",
                      collapse = TRUE,
                      warning = FALSE,
                      message = FALSE)
xaringanExtra::use_panelset()
```

\renewcommand{\figurename}{Fig. S}

```{r warning=FALSE, message=FALSE, echo=FALSE}
library(EnvRtype)
library(rio)
library(factoextra)
library(FactoMineR)
library(ggrepel)
library(ggh4x)
library(superheat)
library(ggridges)
library(tidyverse)
library(metan)
library(rnaturalearth)

my_theme <- 
  theme_bw() +
  theme(panel.spacing = unit(0, "cm"),
        panel.grid = element_blank(),
        legend.position = "bottom")
```


```{r echo=FALSE}
df_traits <- import("https://bit.ly/df_traits")

# grain yield mean in each environment
df_gy <-
  df_traits |>
  means_by(ENV, .vars = GY)

df_var <- 
  df_traits |> 
  means_by(ENV, GEN, .vars = GY) |> 
  var_by(ENV) |> 
  rename(VAR = GY)

```



```{r echo=FALSE}
env_data_me <- import("https://bit.ly/df_climate")
env_data <- env_data_me |> remove_cols(me)

```

```{r echo=FALSE}
# long format for climate data
env_data_d <-
  env_data_me |>
  remove_cols(env, prec, LON:YYYYMMDD, daysFromStart) |>
  pivot_longer(-me)

# long format for grain yield
df_gy_dist <- 
  df_traits |> 
  select(me, GY) |> 
  mutate(name = "GY", .after = me) |> 
  rename(value = GY)


```


# Figure S1  {-}
```{r echo=FALSE, fig.cap="Distribution of climate variables in the different mega-environments"}
# bind climate and GY
env_data_d <- rbind(df_gy_dist, env_data_d)
# mean values for each trait
env_data_mean <- means_by(env_data_d, name)
env_data_memean <- means_by(env_data_d, name, me)

ggplot(env_data_d, aes(x = value, y = me, fill = me)) +
  geom_density_ridges(scale = 0.9) +
  geom_vline(data = env_data_mean,
             aes(xintercept = value),
             linetype = 2) +
  facet_grid(~name, scales = "free") +
  theme(panel.grid.minor = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank()) +
  scale_y_discrete(expand = expansion(c(0, 0.05))) +
  labs(x = "Observed value",
       y = "Density",
       fill = "") +
  my_theme


```





# Figure S2  {-}

```{r echo=FALSE, fig.cap="contribution of variables"}
pca <- 
  import("https://bit.ly/df_pca") |> 
  column_to_rownames("env")


# compute the PCA with

pca_model <- PCA(pca,
                 quali.sup = 14,
                 graph = FALSE)

# contribution of variables
fviz_contrib(pca_model, choice = "var")


```



# Figure S3 {-}
```{r echo=FALSE}
names.window <- c('1-intial growing','2-leaf expansion I','3-leaf expansion II','4-flowering','5-grain filling', "")

out <- 
  env_typing(env.data = env_data,
             env.id = "env",
             var.id = c("sihs", "tmax", "tmin", "dbp", "etp", "vpd", "rh"),
             by.interval = TRUE,
             time.window = c(0, 15, 35, 65, 90, 120),
             names.window = names.window)

mes <- 
  distinct(df_traits, ENV, .keep_all = TRUE) |> 
  select(ENV, me)

out2 <- 
  separate(out,
           env.variable,
           into = c("var", "freq"),
           sep = "_",
           extra = "drop") |> 
  left_join(mes, by = c("env" = "ENV"))

```


```{r echo=FALSE, fig.cap="Quantiles for deficit by precipitation observed in the studied environments (a) and mega-environments (b) across distinct crop stages.", fig.width=13, fig.height=7}

# plot the distribution of envirotypes for dbp
variable <- "dbp"
p1 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  as_factor(freq) |> 
  mutate(freq = fct_relevel(freq, "(-2.25,48.9]", "(-7.62,-2.25]", "(-9.94,-7.62]", "(-13.1,-9.94]")) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=env,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_grid(me~interval, scales = "free", space = "free")+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the deficit by precipitation')+ 
  ylab("Environment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom')

# by mega environment
p2 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  sum_by(me, freq, interval) |> 
  as_factor(freq) |> 
  mutate(freq = fct_relevel(freq, "(-2.25,48.9]", "(-7.62,-2.25]", "(-9.94,-7.62]", "(-13.1,-9.94]")) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=me,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_wrap(~interval, nrow = 1)+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the deficit by precipitation')+ 
  ylab("Mega\nenvironment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom') +
  scale_fill_discrete(direction = 1)

arrange_ggplot(p1, p2, 
               heights = c(0.85, 0.15),
               tag_levels = "a",
               guides = "collect")
```


# Figure S4 {-}

```{r echo=FALSE, fig.cap="Quantiles of maximum temperature observed in the studied environments (a) and mega-environments (b) across distinct crop stages.", fig.width=13, fig.height=7}

# plot the distribution of envirotypes for dbp
variable <- "tmax"
p1 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  ggplot() + 
  geom_bar(aes(x=Freq, y=env,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_grid(me~interval, scales = "free", space = "free")+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the maximum temperature (ºC)')+ 
  ylab("Environment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom')

# by mega environment
p2 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  sum_by(me, freq, interval) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=me,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_wrap(~interval, nrow = 1)+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the maximum temperature (ºC)')+ 
  ylab("Mega\nEnvironment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom') +
  scale_fill_discrete(direction = 1)

arrange_ggplot(p1, p2, 
               heights = c(0.85, 0.15),
               tag_levels = "a",
               guides = "collect")

```





# Figure S5 {-}

```{r echo=FALSE, fig.cap="Quantiles of minimum temperature observed in the studied environments (a) and mega-environments (b) across distinct crop stages.", fig.width=13, fig.height=7}

# plot the distribution of envirotypes for dbp
variable <- "tmin"
p1 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  ggplot() + 
  geom_bar(aes(x=Freq, y=env,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_grid(me~interval, scales = "free", space = "free")+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the minimum temperature (ºC)')+ 
  ylab("Environment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom')

# by mega environment
p2 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  sum_by(me, freq, interval) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=me,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_wrap(~interval, nrow = 1)+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the minimum temperature (ºC)')+ 
  ylab("Mega\nEnvironment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom') +
  scale_fill_discrete(direction = 1)

arrange_ggplot(p1, p2, 
               heights = c(0.85, 0.15),
               tag_levels = "a",
               guides = "collect")

```



# Figure S6 {-}

```{r echo=FALSE, fig.cap="Quantiles of relative humidity observed in the studied environments (a) and mega-environments (b) across distinct crop stages.", fig.width=13, fig.height=7}

# plot the distribution of envirotypes for dbp
variable <- "rh"
p1 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  ggplot() + 
  geom_bar(aes(x=Freq, y=env,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_grid(me~interval, scales = "free", space = "free")+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the relative humidity (%)')+ 
  ylab("Environment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom')

# by mega environment
p2 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  sum_by(me, freq, interval) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=me,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_wrap(~interval, nrow = 1)+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the relative humidity (%)')+ 
  ylab("Mega\nEnvironment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom') +
  scale_fill_discrete(direction = 1)

arrange_ggplot(p1, p2, 
               heights = c(0.85, 0.15),
               tag_levels = "a",
               guides = "collect")

```



# Figure S7 {-}

```{r echo=FALSE, fig.cap="Quantiles of all sky insolation incident on a horizontal surface observed in the studied environments (a) and mega-environments (b) across distinct crop stages.", fig.width=13, fig.height=7}

# plot the distribution of envirotypes for dbp
variable <- "sihs"
p1 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  ggplot() + 
  geom_bar(aes(x=Freq, y=env,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_grid(me~interval, scales = "free", space = "free")+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the all sky insolation incident on a horizontal surface')+ 
  ylab("Environment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom')

# by mega environment
p2 <- 
  out2 |> 
  subset(var == variable) |> # change the variable here
  sum_by(me, freq, interval) |> 
  ggplot() + 
  geom_bar(aes(x=Freq, y=me,fill=freq), 
           position = "fill",
           stat = "identity",
           width = 1,
           color = "white",
           size=.2)+
  facet_wrap(~interval, nrow = 1)+ 
  scale_y_discrete(expand = c(0,0))+
  scale_x_continuous(expand = c(0,0))+
  xlab('Relative frequency of the all sky insolation incident on a horizontal surface')+ 
  ylab("Mega\nEnvironment")+
  labs(fill='Envirotype')+
  theme(axis.title = element_text(size=12),
        legend.text = element_text(size=9),
        strip.text = element_text(size=12),
        legend.title = element_text(size=12),
        strip.background = element_rect(fill="gray95",size=1),
        legend.position = 'bottom') +
  scale_fill_discrete(direction = 1)

arrange_ggplot(p1, p2, 
               heights = c(0.85, 0.15),
               tag_levels = "a",
               guides = "collect")

```




```{r echo=FALSE}
mod_global <- readRDS("data/mod_global.RData")
## mtsi global
SI <- 25
mtsi_global <- mtsi(mod_global, SI = SI, verbose = FALSE)
sel_gen <- mtsi_global$sel_gen
```



```{r echo=FALSE}
mod_me <- readRDS("data/mod_me.RData")
```



```{r include=FALSE}
## mtsi me1
mtsi_me1 <- mtsi(mod_me$data[[1]], SI = SI, verbose = FALSE)
## mtsi me2
mtsi_me2 <- mtsi(mod_me$data[[2]], SI = SI, verbose = FALSE)
## mtsi me3
mtsi_me3 <- mtsi(mod_me$data[[3]], SI = SI, verbose = FALSE)

```



# Figure S8 {-}
```{r fig.width=12, fig.cap="Phenotypic correlation between the studied traits within ME1 (a), ME2 (b), and ME3 (c).", echo=FALSE}

corM1 <- gmd(mod_me$data[[1]], "pcor")


corM1p <- 
  corM1 |>
  network_plot(legend_position = "bottom",
               min_cor = 0.2)

corM2 <-  gmd(mod_me$data[[2]], "pcor")
corM2p <- 
  corM2 |>
  network_plot(legend_position = "bottom",
               min_cor = 0.2)
corM3 <-  gmd(mod_me$data[[3]], "pcor")
corM3p <- 
  corM3 |>
  network_plot(legend_position = "bottom",
               min_cor = 0.2)

arrange_ggplot(corM1p, corM2p, corM3p,
               guides = "collect",
               tag_levels = "a")

bind_cols(corr_focus(corM1, GY) |> rename(GY_ME1 = GY), 
          corr_focus(corM2, GY)[,2] |> rename(GY_ME2 = GY),
          corr_focus(corM3, GY)[,2] |> rename(GY_ME3 = GY))
```

# Figure S9 {-}
```{r fig.cap="Mantel's correlation between the phenotypic correlation matrices observed in each mega-environment", echo=FALSE}

pairs_mantel(as.lpcor(corM1, corM2, corM3),
             names = c("ME1", "ME2", "ME3"))
```



# Figure S10  {-}
```{r fig.width=10, fig.height=10, fig.cap="The strengths and weaknesses view of the selected genotypes is shown as the proportion of each factor on the computed multi-trait stability index (MTSI). The smallest the proportion explained by a factor (closer to the external edge), the closer the traits within that factor are to the ideotype. The dashed line shows the theoretical value if all the factors had contributed equally.", echo=FALSE}

m1 <- plot(mtsi_global, type = "contribution")
m2 <- plot(mtsi_me1, type = "contribution")
m3 <- plot(mtsi_me2, type = "contribution")
m4 <- plot(mtsi_me3, type = "contribution")

arrange_ggplot(m1, m2, m3, m4,
               tag_levels = "a",
               ncol = 2)
```



# Figure S11 {- .panelset}

## ALL  {-}

```{r fig.width=10, fig.height=6, fig.cap="Average value for the studied trait considerig all the environments", echo=FALSE}
ALL <- mtsi_global$sel_gen
ME1 <- mtsi_me1$sel_gen
ME2 <- mtsi_me2$sel_gen
ME3 <- mtsi_me3$sel_gen

mean_all <- 
  df_traits |> 
  pivot_longer(GMC:HSW) |> 
  mutate(selected = ifelse(GEN %in% ALL, "selected", "non-selected"),
         sense = ifelse(name %in% c("BTL", "EH", "GMC", "PH"),
                        "reduce", "increase"),
         GEN = fct_relevel(GEN, paste0("G", 1:26)))
mean_traits_all <- means_by(mean_all, name, sense)


ggplot(mean_all, aes(value, GEN)) +
  geom_boxplot(aes(fill = selected),
               outlier.colour = "transparent",
               size = 0.1) +
  stat_summary(fun = mean,
               geom = "point",
               shape = "diamond") +
  facet_nested(~sense+name, scales  = "free_x") +
  geom_vline(aes(xintercept = value),
             data = mean_traits_all,
             color = "blue") +
  labs(x = "Observed value (average)",
       y = "Genotypes") +
  theme(legend.position = "bottom") +
  my_theme
```


## ME1  {-}

```{r fig.width=10, fig.height=6, fig.cap="Average value for the studied trait across ME1", echo=FALSE}
mean_me1 <- 
  df_traits |> 
  filter(me == "ME1") |> 
  pivot_longer(GMC:HSW) |> 
  mutate(selected = ifelse(GEN %in% ME1, "selected", "non-selected"),
         sense = ifelse(name %in% c("BTL", "EH", "GMC", "PH"),
                        "reduce", "increase"),
         GEN = fct_relevel(GEN, paste0("G", 1:26)))
mean_traits_me1 <- means_by(mean_me1, name, sense)


ggplot(mean_me1, aes(value, GEN)) +
  geom_boxplot(aes(fill = selected),
               outlier.colour = "transparent",
               size = 0.1) +
  stat_summary(fun = mean,
               geom = "point",
               shape = "diamond") +
  facet_nested(~sense+name, scales  = "free_x") +
  geom_vline(aes(xintercept = value),
             data = mean_traits_me1,
             color = "blue") +
  labs(x = "Observed value (average)",
       y = "Genotypes") +
  theme(legend.position = "bottom") +
  my_theme
```


## ME2  {-}

```{r fig.width=10, fig.height=6, fig.cap="Average value for the studied trait across ME2", echo=FALSE}
mean_me2 <- 
  df_traits |> 
  filter(me == "ME2") |> 
  pivot_longer(GMC:HSW) |> 
  mutate(selected = ifelse(GEN %in% ME2, "selected", "non-selected"),
         sense = ifelse(name %in% c("BTL", "EH", "GMC", "PH"),
                        "reduce", "increase"),
         GEN = fct_relevel(GEN, paste0("G", 1:26)))
mean_traits_me2 <- means_by(mean_me2, name, sense)


ggplot(mean_me2, aes(value, GEN)) +
  geom_boxplot(aes(fill = selected),
               outlier.colour = "transparent",
               size = 0.1) +
  stat_summary(fun = mean,
               geom = "point",
               shape = "diamond") +
  facet_nested(~sense+name, scales  = "free_x") +
  geom_vline(aes(xintercept = value),
             data = mean_traits_me2,
             linetype = 2) +
  labs(x = "Observed value (average)",
       y = "Genotypes") +
  theme(legend.position = "bottom") +
  my_theme
```

## ME3  {-}

```{r fig.width=10, fig.height=6, fig.cap="Average value for the studied trait across ME3", echo=FALSE}
mean_me3 <- 
  df_traits |> 
  filter(me == "ME3") |> 
  pivot_longer(GMC:HSW) |> 
  mutate(selected = ifelse(GEN %in% ME3, "selected", "non-selected"),
         sense = ifelse(name %in% c("BTL", "EH", "GMC", "PH"),
                        "reduce", "increase"),
         GEN = fct_relevel(GEN, paste0("G", 1:26)))
mean_traits_me3 <- means_by(mean_me3, name, sense)


ggplot(mean_me3, aes(value, GEN)) +
  geom_boxplot(aes(fill = selected),
               outlier.colour = "transparent",
               size = 0.1) +
  stat_summary(fun = mean,
               geom = "point",
               shape = "diamond") +
  facet_nested(~sense+name, scales  = "free_x") +
  geom_vline(aes(xintercept = value),
             data = mean_traits_me3,
             color = "blue") +
  labs(x = "Observed value (average)",
       y = "Genotypes") +
  theme(legend.position = "bottom") +
  my_theme
```



# Figure S12  {-}
```{r fig.width=12, fig.height=8, echo=FALSE}
ge_plot(df_traits, ENV, GEN, GY,
        order_g = paste0("G", 1:26))
```


# Figure S13  {-}
```{r fig.width=12, fig.height=6, echo=FALSE}
ge_plot(df_traits, me, GEN, GY,
        order_g = paste0("G", 1:26))
```

